baseURL = 'https://spine.io/'
languageCode = 'en-us'
title = 'Spine Event Engine'
disableKinds = ['taxonomy', 'term']

[params]
  defaultCodeTheme = 'dark'

# Enables HTML rendering in markdown files.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    noClasses = false
