[module]
  [[module.imports]]
    path = 'github.com/twbs/bootstrap'
    disable = false
  [[module.imports.mounts]]
    source = 'scss'
    target = 'assets/bootstrap/scss'
  [[module.imports.mounts]]
    source = 'js/dist'
    target = 'assets/bootstrap/dist/js'
